name: Bundle release

on:
  release:
    types: [ published ]
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Prevent multiple unnecessary CI runs on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle:
    name: Add zip to release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4' ]
        node: [ 'latest' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: PHP setup
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      # Composer.
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: '--no-dev'

      # Npm.
      - name: Set Node.js version - ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install node packages
        run: npm install

      # Zip.
      - name: Bundle assets
        run: npm run build --no-dev --no-progress

      - name: Move bundled files to a subfolder and zip
        run: |
          chmod +x "$GITHUB_WORKSPACE/bin/bundle-plugin.sh"
          bash "$GITHUB_WORKSPACE/bin/bundle-plugin.sh" "$GITHUB_WORKSPACE"
        shell: bash

      - name: Zip Folder
        run: zip -r release.zip eightshift-forms

      # Upload
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'release.zip'
          tag: ${{ github.ref }}
          overwrite: true
