name: Continuous integration checks

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Prevent multiple unnecessary CI runs on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Lint JS and CSS files.
  lint:
    name: File linting using Node version - ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 'latest' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version - ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install node packages
        run: npm install

      - name: Run linters
        run: npm run lintJs && npm run lintStyle

  # PHP check coding standards.
  phpcs:
    name: PHPCS check on PHP version - ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: cs2pr

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Check coding standards using PHPCS
        run: composer test:standards -- --runtime-set testVersion ${{ matrix.php }}- --report-full --report-checkstyle=./phpcs-report.xml

      - name: Show PHPCS results in PR
        run: cs2pr ./phpcs-report.xml

  # PHP Static code analaysis.
  phpstan:
    name: PHPStan check on PHP version - ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run PHP Static code analaysis
        run: composer test:types
